In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# visualization
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


# machine learning
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report,accuracy_score
from sklearn.ensemble import IsolationForest

In [2]:
df=pd.read_csv('creditcard.csv', sep=',')
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.919560e-15  5.688174e-16 -8.769071e-15  2.782312e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552563e-15  2.010663e-15 -1.694249e-15 -1.927028e-16 -3.137024e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

           ...                 V21           V22           V23           V24  \
count      ...        2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean       ...        1.537294e-16  7.959909e-16  5.367590e-16  4.458112e-15   
std        ...        7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min        ...       -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%        ...       -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%        ...       -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%        ...        1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max        ...        2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.453003e-15  1.699104e-15 -3.660161e-16 -1.206049e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [3]:
inliers = df[df.Class==0]
inliers = inliers.drop(['Class'], axis=1)
outliers = df[df.Class==1]
outliers = outliers.drop(['Class'], axis=1)
inliers_train, inliers_test = train_test_split(inliers, test_size=0.30, random_state=42)


In [4]:
model = IsolationForest(n_estimators=110,max_features=5,bootstrap=False,contamination=0.01,max_samples=500,verbose=1,n_jobs=4,random_state=42)
model.fit(df.drop(['Class'], axis=1))
inlier_pred_train=model.predict(inliers_train)
inlier_pred_test=model.predict(inliers_test)
outlier_pred_test=model.predict(outliers)

[Parallel(n_jobs=4)]: Done   2 out of   4 | elapsed:    0.9s remaining:    0.9s
[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    1.0s finished


In [5]:
print("Accuracy in Detecting Legit Cases:", list(inlier_pred_test).count(1)/inlier_pred_test.shape[0])
print("Accuracy in Detecting Fraud Cases:", list(outlier_pred_test).count(-1)/outlier_pred_test.shape[0])

Accuracy in Detecting Legit Cases: 0.9912656075971628
Accuracy in Detecting Fraud Cases: 0.6422764227642277


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Class'],axis=1), df.Class, test_size=0.3, random_state=42)

In [7]:
y_pred_train=model.predict(X_train)
y_pred_test=model.predict(X_test)
y_pred_train[y_pred_train==1]=0
y_pred_train[y_pred_train==-1]=1
y_pred_test[y_pred_test==1]=0
y_pred_test[y_pred_test==-1]=1


In [8]:
roc_auc_score(y_train,y_pred_train)

0.81158679070662398

In [9]:
roc_auc_score(y_test,y_pred_test)

0.83003398969397035

In [10]:
from sklearn.metrics import f1_score
f1_score(y_train,y_pred_train)

0.19214346712211786

In [11]:
f1_score(y_test,y_pred_test)

0.18218218218218218

In [12]:
print(classification_report(y_train,y_pred_train))


             precision    recall  f1-score   support

          0       1.00      0.99      1.00    199008
          1       0.11      0.63      0.19       356

avg / total       1.00      0.99      0.99    199364



In [13]:
print(classification_report(y_test,y_pred_test))


             precision    recall  f1-score   support

          0       1.00      0.99      1.00     85307
          1       0.11      0.67      0.18       136

avg / total       1.00      0.99      0.99     85443



In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train,y_pred_train))


[[197247   1761]
 [   131    225]]


In [17]:
confusion_matrix(y_test,y_pred_test)

array([[84535,   772],
       [   45,    91]])

In [18]:
outlier_pred_test[outlier_pred_test==-1]=1
outlier_pred_test[outlier_pred_test==1]=0

In [19]:
clf=IsolationForest(n_estimators=150,max_features=9,max_samples=5500,bootstrap=True,contamination=0.001,n_jobs=-1)

In [20]:
clf.fit(X_train)

IsolationForest(bootstrap=True, contamination=0.001, max_features=9,
        max_samples=5500, n_estimators=150, n_jobs=-1, random_state=None,
        verbose=0)

In [21]:
y_pred_train=clf.predict(X_train)
y_pred_test=clf.predict(X_test)

In [22]:
y_pred_train[y_pred_train==1]=0
y_pred_train[y_pred_train==-1]=1
y_pred_test[y_pred_test==1]=0
y_pred_test[y_pred_test==-1]=1

In [23]:
print(classification_report(y_train,y_pred_train))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00    199008
          1       0.40      0.22      0.28       356

avg / total       1.00      1.00      1.00    199364



In [24]:
print(classification_report(y_test,y_pred_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     85307
          1       0.49      0.30      0.37       136

avg / total       1.00      1.00      1.00     85443



In [25]:
roc_auc_score(y_train,y_pred_train)

0.61065104830069505

In [26]:
roc_auc_score(y_test,y_pred_test)

0.65048326321748651

In [27]:
len(y_pred_test[y_test!=y_pred_test])


138

In [28]:
len(y_pred_train[y_train!=y_pred_train])

398

In [29]:
from sklearn.metrics import confusion_matrix


In [30]:
confusion_matrix(y_train,y_pred_train)

array([[198887,    121],
       [   277,     79]])

In [31]:
confusion_matrix(y_test,y_pred_test)

array([[85264,    43],
       [   95,    41]])

In [32]:
df.head()


Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [36]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
scaled_df=scale.fit_transform(df)
y=df.Class

In [37]:
scaled_df=pd.DataFrame(scaled_df)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df, y, test_size=0.3, random_state=42)

In [39]:
clf_scaled=IsolationForest(n_estimators=110,bootstrap=False,max_features=1.0,contamination=0.001,max_samples=5500,verbose=3,n_jobs=-1)

In [40]:
clf_scaled.fit(X_train)

Building estimator 1 of 28 for this parallel run (total 110)...
Building estimator 1 of 28 for this parallel run (total 110)...
Building estimator 1 of 27 for this parallel run (total 110)...
Building estimator 2 of 28 for this parallel run (total 110)...
Building estimator 2 of 28 for this parallel run (total 110)...
Building estimator 2 of 27 for this parallel run (total 110)...
Building estimator 1 of 27 for this parallel run (total 110)...
Building estimator 3 of 28 for this parallel run (total 110)...
Building estimator 3 of 28 for this parallel run (total 110)...
Building estimator 3 of 27 for this parallel run (total 110)...
Building estimator 4 of 28 for this parallel run (total 110)...
Building estimator 4 of 28 for this parallel run (total 110)...
Building estimator 2 of 27 for this parallel run (total 110)...
Building estimator 4 of 27 for this parallel run (total 110)...
Building estimator 5 of 28 for this parallel run (total 110)...
Building estimator 3 of 27 for this para

[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    3.1s finished


IsolationForest(bootstrap=False, contamination=0.001, max_features=1.0,
        max_samples=5500, n_estimators=110, n_jobs=-1, random_state=None,
        verbose=3)

In [41]:
y_pred_train=clf_scaled.predict(X_train)
y_pred_test=clf_scaled.predict(X_test)

In [42]:
y_pred_train[y_pred_train==1]=0
y_pred_train[y_pred_train==-1]=1
y_pred_test[y_pred_test==1]=0
y_pred_test[y_pred_test==-1]=1

In [43]:
print(classification_report(y_test,y_pred_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     85307
          1       0.58      0.34      0.43       136

avg / total       1.00      1.00      1.00     85443



In [44]:
print(classification_report(y_train,y_pred_train))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00    199008
          1       0.48      0.27      0.35       356

avg / total       1.00      1.00      1.00    199364



In [45]:
len(y_pred_test[y_test!=y_pred_test])


123

In [46]:
len(y_pred_train[y_train!=y_pred_train])


364

In [47]:
confusion_matrix(y_train,y_pred_train)

array([[198904,    104],
       [   260,     96]])

In [48]:
confusion_matrix(y_test,y_pred_test)

array([[85274,    33],
       [   90,    46]])

In [49]:
roc_auc_score(y_train,y_pred_train)

0.63457016464585692

In [50]:
roc_auc_score(y_test,y_pred_test)

0.66892422799590967